const SWAP_STATUS_UNSIGNED = 0;
const SWAP_STATUS_SIGNED = 1;
const SWAP_STATUS_SUBMITTED = 2;
const SWAP_STATUS_CONFIRMED = 3;

module.exports = { 
    SWAP_STATUS_UNSIGNED,
    SWAP_STATUS_SIGNED,
    SWAP_STATUS_SUBMITTED,
    SWAP_STATUS_CONFIRMED
}